plugins {
    id 'brava.spring-boot-conventions'
}

dependencies {
    api project(':core')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
}

tasks.named('test') {
    useJUnitPlatform()
}

/* Used to expose a port for debugging backend
tasks.named("bootRun") {
    jvmArgs = [
            "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ]
}
*/
